name: bayes-beat
channels:
  - conda-forge
dependencies:
  - numpy
  - pytorch-cpu
  - nessai
  - pycondor
  - hdf5storage
  - h5py
  - corner
  - dill
  - simple_slurm
  - numba
  - click
  - seaborn
  - sympy
