name: bayes-beat
channels:
  - pytorch
  - astropy
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - cpuonly
  - nessai
  - pycondor
  - hdf5storage
  - h5py
  - corner
  - dill
  - simple_slurm
  - numba
  - click
  - seaborn
  - sympy
